pipeline {
  agent any
  stages {
    stage('BuildApplication') {
      steps {
         sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
      }
      post {
        success {
            echo "we are archiving the artifact"
            archiveArtifacts artifacts: '**/*.war', followSymlinks: false
        }
      }
     }
    stage('Build') {
      steps {
	 echo "We are inside build stage, building the code now"
	}
	}
    stage('Deploy'){
      steps {
	echo "We are deploy the app"
	}
	}
   }
}
