pipeline{
    agent: any
  stages{
    stage('Initialization'){
        steps{
            echo "We are in the initialization stage"
            }
        }
    stage('Build'){
        steps{
            echo "We are in the build stage"
            }
        }
    stage('Deploy'){
        steps{
            echo "We are in the Deploy stage"
            }
        }
    }
}
