pipeline{
    agent{
        label 'slave-node-javaapp'
    }
  stages{
    stage('Build'){
        steps{
            echo "We are in the build stage"
            sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
            echo "Building completed."
                        }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
            }
            }
        }
        stage('Create Tomcat Image') {
            agent {
                label 'slave-node-javaapp'
            }
            steps {
                copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
                echo "Building docker image"
                sh '''
                original_pwd=$(pwd -P)
                cd jenkins/java-tomcat-sample
                docker build -t localtomcatimg:$BUILD_NUMBER .
                cd $original_pwd
                sh '''
            }
        }
    stage('Deploy QA instance'){
        steps{
            echo "We are in the deploy stage"
            }
        }
    stage('Deploy Production instance'){
        steps{
            echo "We are in the Production stage"
            }
        }
    }
}
